# Generated by Django 4.2.7 on 2023-12-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=120)),
                ('taskDecision', models.TextField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('TaskAsaignDate', models.DateField()),
            ],
        ),
    ]
