# Generated by Django 4.2.7 on 2023-12-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_car_quantity_alter_car_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.FileField(blank=True, null=True, upload_to='car/media/uploads/'),
        ),
    ]
