# Generated by Django 4.2.7 on 2023-12-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_brand_slug'),
        ('car', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='BuyedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.FileField(blank=True, null=True, upload_to='car/media/uploads/')),
                ('car_name', models.CharField(max_length=150)),
                ('car_price', models.CharField(blank=True, max_length=100, null=True)),
                ('car_quantity', models.IntegerField(blank=True, null=True)),
                ('car_brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
            ],
        ),
    ]
