# Generated by Django 4.2.7 on 2023-12-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_buyedcar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyedcar',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
